version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    image: rabbitmq:3-management

  api:
    image: peddledonetcore:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 5000:80
        - 5001:443
    depends_on:
        - rabbitmq